### ISSUE TITLE
Stacktape Launch Week 

### ISSUE THREAD

**Issue by liracinai** [supabase-community/launchweek.dev#18]
Stacktape Launch Week 
2024 / 03 / 4-8
https://stacktape.com

**Comment by fmerian** [comment]
thanks for the suggestion, @liracinai! that’s awesome. 

do you have a thread or a blog announcement that we could add/refer to?

**Comment by liracinai** [comment]
https://x.com/stacktape/status/1763511418316325097

**Comment by liracinai** [comment]
Sorry, have to change it for 2024 / 03 / 11-15  -> https://x.com/stacktape/status/1763519425670521286?s=20

**Comment by fmerian** [comment]
you're in, @liracinai! enjoy your launch week!

**Comment by liracinai** [comment]
Thank you 🤩
