### ISSUE TITLE
Add Nakuru Launch Week

### ISSUE THREAD

**Issue by Cheppar** [supabase-community/launchweek.dev#60]
Launch Week 13 Nakuru, Kenya.
Date: 6/12/2024
https://bit.ly/3Cx3WUV

**Comment by fmerian** [comment]
thanks for the suggestion, @Cheppar! to clarify, is it a week of announcements or an event related to Supabase LW13?

**Comment by Cheppar** [comment]
@fmerian the event is associated with Supabase LW13 that will be hosted in Nakuru, Kenya.

**Comment by fmerian** [comment]
@Cheppar thanks for clarification! unfortunately, this repo lists launch weeks, ie. companies announcing new features for a week — not events. that would be an idea for another awesome list, tho!

sorry for the confusion here — closing the issue — and enjoy your event!
