### ISSUE TITLE
How to get added on annoucements page? 

### ISSUE THREAD

**Issue by bhaktatejas922** [supabase-community/launchweek.dev#95]
Cant see any of our announcements on the announcements page. 

Not sure if theres a PR im supposed to make somewhere or what. Ex: https://airpinpoint.com/en/launch-week/day2 https://x.com/airpinpoint/status/1863893170309959985

**Comment by fmerian** [comment]
thanks for the report, @bhaktatejas922! feel free to edit this page: `lw/MEGA.mdx`

**Comment by fmerian** [comment]
solved with #98
